#!/usr/bin/env python

"""
seq_tools: general tools for working with sequence files

Usage:
  seq_tools [options] <command> [<args>...]
  seq_tools -p <perl_command>
  seq_tools -h | --help
  seq_tools --version

Options:
  -p --perldoc  Get perldoc of Perl command.
  -h --help     Show this screen.
  --version     Show version.

Commands:
  fasta_info     General info on fasta file
  fasta_unwrap   Unwrap a fasta file
  filter_seq     Filter sequences
  seqIntersect   Intersection of 2 sequence files
  

Description:
  This is the main command to call various scripts associated with this project.
"""

import os, sys
from docopt import docopt
from subprocess import call

scriptDir = os.path.dirname(__file__)
subcmdDir = os.path.join(scriptDir, 'bin')

if __name__ == '__main__':
    args = docopt(__doc__,
                  version='0.1',
                  options_first=True)


    # subcommand script
    exts = ['.pl', '.py', '.r']
    scriptFiles = [os.path.join(subcmdDir, args['<command>'] + ext) for ext in exts]
    scriptFiles = filter(os.path.isfile, scriptFiles)
    if len(scriptFiles) < 1:
        msg = '"{}" is not a valid command. See "seq_tools -h".' 
        exit(msg.format(args['<command>']))

    
    # calling subcommand script
    cmd = [scriptFiles[0]] + args['<args>']
    if args['--perldoc']:
        cmd = ['perldoc'] + cmd    

    exit(call(cmd))
